create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  reference_id text not null unique,
  created_at timestamptz not null default now(),
  full_name text not null,
  business_email text not null,
  company_name text not null,
  hiring_needs text not null,
  language text not null default 'en',
  source text not null default 'landing-contact-form'
);

create index if not exists contact_submissions_created_at_idx
  on public.contact_submissions (created_at desc);
